### ISSUE TITLE
Weak Cryptographic Hash

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [NetApp/eseries-perf-analyzer#10]
https://github.com/NetApp/eseries-perf-analyzer/blob/67c9c3059d40a668b3598ffcbde1559fb98f910f/plugins/eseries_monitoring/collector/collector.py#L526

In systems with high security requirements, sha-series algorithms (such as sha-224, sha-256, sha-384, and sha-512) with a hash value of >=224 bits should be used to ensure the integrity of sensitive data

**Comment by scaleoutsean** [comment]
This looks meaningless. Close it?
