### ISSUE TITLE
Issue with make run at step 10/10

### ISSUE THREAD

**Issue by GSCDROM** [NetApp/eseries-perf-analyzer#12]
Hi

The setup keeps getting stuck at stage 10 with the error shown below, any tips on what the issue could be. The perf analysis was actually up and running for a while, but then somehow failed, and now this error is encountered each time -

# Start an instance of our Ansible image to perform setup on the running instance
docker run --rm --network=container:grafana ntap-grafana/ansible:2.1
No config file found; using defaults
[WARNING]: provided hosts list is empty, only localhost is available. Note that
the implicit localhost does not match 'all'

PLAY [localhost] ***************************************************************

TASK [Gathering Facts] *********************************************************
ok: [localhost]

TASK [include_tasks] ***********************************************************
included: /home/tasks/grafana.yml for localhost

TASK [Wait for InfluxDB to startup completely] *********************************
ok: [localhost] => {"changed": false, "elapsed": 2, "match_groupdict": {}, "match_groups": [], "path": null, "port": 8086, "search_regex": null, "state": "started"}

TASK [Get influxdb datasource] *************************************************
fatal: [localhost]: FAILED! => {"cache_control": "no-cache", "changed": false, "connection": "close", "content_length": "42", "content_type": "application/json; charset=UTF-8", "date": "Mon, 04 Jan 2021 15:56:15 GMT", "elapsed": 0, "expires": "-1", "json": {"message": "Invalid username or password"}, "msg": "Status code was 401 and not [404, 200]: HTTP Error 401: Unauthorized", "pragma": "no-cache", "redirected": false, "status": 401, "url": "http://grafana:3000/api/datasources/id/WSP", "x_frame_options": "deny"}

PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

make: *** [run] Error 2
[root@PHCGRAFANA02 eseries-perf-analyzer]#

**Comment by scaleoutsean** [comment]
Grafana can't access InfluxDB. Ensure that [config details](https://github.com/NetApp/eseries-perf-analyzer/blob/67c9c3059d40a668b3598ffcbde1559fb98f910f/ansible/main.yml) are correct (including datastore.json) and you executed from the right location as user who has permissions to these files. It could be many things but end result is Grafana can't access InfluxDB.

**Comment by scaleoutsean** [comment]
Can this be closed?

**Comment by gmarks-ntap** [comment]
I was leaving it for the creator to close, but I'll close it since it should be fixed.
