### ISSUE TITLE
Can not install

### ISSUE THREAD

**Issue by fbijma2** [NetApp/eseries-perf-analyzer#5]
When I do make run I get the following:

 make run
chmod +x scripts/*
scripts/images.sh
##########################################################################################
In order to run this application the following Docker images will be downloaded and installed:
alpine:3.10
grafana/grafana:6.3.2
graphiteapp/graphite-statsd:1.1.5-11
influxdb:1.7-alpine
netapp/eseries-webservices:3.20
python:3.7-alpine3.10

If you agree with the above you may continue, otherwise cancel and
  change the relevant tags to a newer version in the Dockerfile[s].
Be aware that the images configured in the repository
  are the tested images and we cannot guarantee correct
  behavior if you update the images to a new tag.
Would you like to continue? [y/n] y
docker build --build-arg REPO_FILE=repositories --build-arg TAG=1.0 -t ntap-grafana/alpine-base:1.0 build/alpine
Sending build context to Docker daemon 4.096 kB
Step 1/6 : ARG TAG=latest
Please provide a source image with `from` prior to commit
make: *** [build] Error 1

**Comment by lmprice** [comment]
@fbijma2 Can you post your Docker version here? I suspect that you may have a version that doesn't support using an ARG as the first step in a Dockerfile (we use this feature in our build process). It looks like 17.05 was the first version that supported this functionality. We also use multi-stage builds which are first supported in 17.05.

**Comment by fbijma2** [comment]
I have used the rhel  7 version  of docker. I'll come back with the
version, but it is 13 something.

Op wo 26 feb. 2020 16:56 schreef Michael Price <notifications@github.com>:

**Comment by scaleoutsean** [comment]
It seems this can be closed.
